### ISSUE TITLE
Compatibility Issues with DataFrames and SortingAlgorithms on Julia 1.11.1

### ISSUE THREAD

**Issue by Marta-Barea** [caseykneale/ChemometricsData.jl#28]
The `ChemometricsData` package cannot be installed on Julia 1.11.1 due to dependency conflicts. The `Manifest.toml` locks `DataFrames` at version `0.21.7` and `SortingAlgorithms` at version `0.3.1`, which are incompatible with modern Julia environments.

### Observations
- `Project.toml` does not explicitly restrict versions for `DataFrames` or `SortingAlgorithms`.
- `Manifest.toml` locks:
  - `DataFrames` at version `0.21.7`
  - `SortingAlgorithms` at version `0.3.1`

### Suggested Solution
1. Update the `Project.toml` file to allow more recent versions of these dependencies:
   ```toml
   [compat]
   DataFrames = "0.21, ^1.0"
   SortingAlgorithms = "0.3, ^1.0"
2. Regenerate the `Manifest.toml` file to resolve compatible versions automatically.

This will ensure the package remains compatible with both older and newer Julia setups.

Thank you for maintaining this package!

**Comment by caseykneale** [comment]
Hello,

This request reads a lot like ChatGPT. Not sure if I should reply or if this is a bot...

I haven't updated this package for many years. Possibly since Julia v0.6 or v0.7. You are welcome to make a Pull Request with these changes if you'd like. I am willing to do it and do some testing, but it may take me a while to get around to updating this. My priorities for open source/chemometrics projects are a lot lower these days than they once were.

**Comment by caseykneale** [comment]
In a day or so, the new release should propagate to Julia's build servers. I hardly tested it, but it seemed to work. The Penicillin dataset may or may not work. You can follow the progress for v0.1.3 here: https://github.com/JuliaRegistries/General/pull/120542

If this doesn't work open a new issue and we can talk through what issues you are seeing. Also, please don't use ChatGPT/LLMs to make issues on my repositories. I enjoy talking to people and more often then not the solutions they offer are incorrect or partial at best.

**Comment by Marta-Barea** [comment]
Hi! Thank you very much for your reply and for taking the time to check it out. No, I'm not a bot. I haven't used Julia as a programming language and that's why I opened the issue. The reply was organized in case it could be helpful to get to the issue kit. And obviously, it was a suggestion. I was quite interested in being able to use some data from the repository because I work with these techniques. Using chatGPT or LLMs is not a bad thing. Although I have to say that's not the case. Possibly more the unfamiliarity with the language. It is also possible that the very technical way spoken is because my native language is not English 😉. Anyway thanks for the advice, for your reply and especially for maintaining the repository 😊

**Comment by caseykneale** [comment]
I am glad you aren't a bot. For not natively speaking English you speak it well. My concern was I didn't want to spend a half hour or so doing some maintenance if it didn't help an actual person. There are a lot of bots posting code changes, and issues on github now days. Some of it is as an "experiment" and some of it is people trying to help but not being confident in trying it themselves. Hopefully when the changes propagate this package will work for your needs. 

Feel free to open issues or find me on social media to have discussions. I don't do Chemometrics anymore, except as a hobby, but it is something I care about and am interested in. It's nice to meet another person with a similar interest.

**Comment by Marta-Barea** [comment]
No problem! Thank you very much for your time and reviewing it! ☺️
